apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    feature-gate.release.openshift.io/: "true"
  name: certificatesigningrequestapprovalslist.hypershift.openshift.io
spec:
  group: hypershift.openshift.io
  names:
    kind: CertificateSigningRequestApprovalList
    listKind: CertificateSigningRequestApprovalListList
    plural: certificatesigningrequestapprovalslist
    singular: certificatesigningrequestapprovallist
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
