/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// ExternalTemplateReferenceApplyConfiguration represents a declarative configuration of the ExternalTemplateReference type for use
// with apply.
type ExternalTemplateReferenceApplyConfiguration struct {
	APIGroup *string `json:"apiGroup,omitempty"`
	Resource *string `json:"resource,omitempty"`
	Name     *string `json:"name,omitempty"`
}

// ExternalTemplateReferenceApplyConfiguration constructs a declarative configuration of the ExternalTemplateReference type for use with
// apply.
func ExternalTemplateReference() *ExternalTemplateReferenceApplyConfiguration {
	return &ExternalTemplateReferenceApplyConfiguration{}
}

// WithAPIGroup sets the APIGroup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIGroup field is set to the value of the last call.
func (b *ExternalTemplateReferenceApplyConfiguration) WithAPIGroup(value string) *ExternalTemplateReferenceApplyConfiguration {
	b.APIGroup = &value
	return b
}

// WithResource sets the Resource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resource field is set to the value of the last call.
func (b *ExternalTemplateReferenceApplyConfiguration) WithResource(value string) *ExternalTemplateReferenceApplyConfiguration {
	b.Resource = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ExternalTemplateReferenceApplyConfiguration) WithName(value string) *ExternalTemplateReferenceApplyConfiguration {
	b.Name = &value
	return b
}
