apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    api.openshift.io/merged-by-featuregates: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
  name: certificatesigningrequestapprovalslist.hypershift.openshift.io
spec:
  group: hypershift.openshift.io
  names:
    kind: CertificateSigningRequestApprovalList
    listKind: CertificateSigningRequestApprovalListList
    plural: certificatesigningrequestapprovalslist
    singular: certificatesigningrequestapprovallist
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
